"""initial schema — append-only record tables

Baseline migration: creates all tables from the ORM metadata (source of truth in
services/persistence/models.py). Subsequent schema changes should use explicit
autogenerated migrations.

Revision ID: 0001
Revises:
Create Date: 2026-09-06
"""
from alembic import op

from services.persistence.models import Base

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(op.get_bind())
